### ISSUE TITLE
Document installation under conda

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#118]
http://biopython.org/wiki/Download should probably have a section about conda, and suggest trying ``conda install biopython``

**Comment by MarkusPiotrowski** [comment]
I just want to mention that Anaconda is usually late with updating its Biopython package, their actual version is still 1.68. Bioconda is up-to-date but doesn't have Windows installers. Maybe worth mentioning when we suggest ```conda install biopython```.

**Comment by peterjc** [comment]
Yes, the default channel only has Biopython 1.68 right now, but covers Windows, Linux and Mac.
https://anaconda.org/anaconda/biopython

As you say, BioConda channel has Biopython 1.69 (see https://github.com/bioconda/bioconda-recipes/pull/4403 - thank you @saketkc), but they currently only provide binaries for 64 bit Linux and Mac OS:
https://anaconda.org/bioconda/biopython

There are several other channels with Biopython, but none that I am familiar with.

**Comment by peterjc** [comment]
Cross reference https://github.com/biopython/biopython/issues/1295

**Comment by peterjc** [comment]
Cross reference https://github.com/biopython/biopython/pull/804

**Comment by souravsingh** [comment]
I would suggest maybe writing a conda recipe for biopython at [conda-forge](https://conda-forge.org/). This should solve the problem for Windows since conda-forge packages binaries for Linux, Mac and Windows. But I am really worried about the recipe clashing with ``bioconda`` channel.

Any suggestions?

**Comment by peterjc** [comment]
Let's ask the BioConda folk via their GitHub?

**Comment by MarkusPiotrowski** [comment]
Maybe another alternative (especially speaking about Windows):
Anaconda and Miniconda both come with pip (according to https://conda.io/docs/using/pkgs.html). So if people are using conda, they should be able to use ```pip install biopython``` in their conda environment, given that Windows-specific wheels are available.

**Comment by souravsingh** [comment]
If I am not wrong, many people avoid using pip within conda, especially when they are using conda environment for their project setup.

**Comment by souravsingh** [comment]
@peterjc The conda recipe is now available here- https://github.com/conda-forge/biopython-feedstock

**Comment by peterjc** [comment]
Checking on https://github.com/bioconda/bioconda-recipes/issues/5292 if BioConda will deprecate their recipe now, or continue to keep it up to date as well.

**Comment by peterjc** [comment]
Conda installation is now documented on http://biopython.org/wiki/Packages with a directly link from http://biopython.org/wiki/Download - belated closing issue.

**Comment by souravsingh** [comment]
@MarkusPiotrowski As you notice, the ``numpy`` is compiled using ``mkl``, which can be a pain since it installs extra Intel packages like the ``intel-openmp``.

You can bypass using MKL for Numpy by using ``conda install nomkl`` which would look for a non-MKL version of related packages as mentioned here- https://www.anaconda.com/blog/developer-blog/anaconda-25-release-now-mkl-optimizations/

This won't work for Windows machines since conda-forge only supports MKL for Windows machines, OpenBLAS has problems for Windows- https://github.com/conda-forge/openblas-feedstock/issues/2

**Comment by souravsingh** [comment]
Also the extra packages in the conda-forge upgrade are the full requirements for the biopython, which include optional requirements like ``reportlab``. I am not sure about how to resolve the optional vs recommended dependency problem with conda, but having complete package installed shouldn't hurt, I guess?

**Comment by MarkusPiotrowski** [comment]
@souravsingh It's still not clear to me: Does the Biopython installation from conda-forge install/upgrade Numpy? It's not obvious to me (I cancelled the installation because I didn't want to install the additional packages).

I use miniconda, thus installing a number of packages which are not mandatory sounds counterintuitive to me. So I will try to get the current Biopython version by ```pip```. You mentioned above that some people don't like to mix conda and pip, but for me it works.

**Comment by peterjc** [comment]
On a technical point, Conda has multiple channels, each of which may provide a Biopython and/or NumPy package, and each of these may define their dependencies differently.

Practically speaking the only channels we care about are:

* https://anaconda.org/anaconda/biopython which is the default channel This currently provides an old version of Biopython, which we have no control over (updates, dependencies, etc)
* https://anaconda.org/bioconda/biopython from the BioConda channel. Currently the most downloaded, but this has been dropped favour of conda-forge package (which also covers Windows), and will not be updated in future.
* https://anaconda.org/conda-forge/biopython the Conda Forge channel, where the source recipe is at https://github.com/conda-forge/biopython-feedstock

Currently the conda-forge receipe requires ``numpy`` (which is good, and they only set minimum versions of numpy for the end user of the package), but also requires ``reportlab`` and ``mmtf-python`` (which is debatable and inconsistent as it misses many other soft dependencies).

I think it makes sense to submit a pull request removing those soft dependencies from the conda-forge recipe for Biopython, but this is essentially down to their packaging policies.

**Comment by peterjc** [comment]
Cross reference https://github.com/conda-forge/biopython-feedstock/pull/3 to modify the ``conda-forge`` package to only install ``numpy`` (and not ``reportlab`` and ``mmtf-python``).
