### ISSUE TITLE
Colon in filenames, serious problem under Windows

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#21]
Colon in filenames are problematic under Windows. When pulling my forked respository to my computer I loose all files that contain a colon. When pushing commits from local I also delete them from remote.
This is a known issue, e.g. see SO questions [here](http://stackoverflow.com/questions/31887697/issue-with-windows-and-git-with-illegal-filenames) and [here](http://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename)
I know, changing the filenames may not be trivial. However, for Windows people (there are some) its hard to participate.

**Comment by peterjc** [comment]
The old URLs have colons in them, and we can't change that. If we did change the page URLs, it would break incoming links.

I tried some experiments with ``%3A`` in the filename (URL escaping the colon), but that didn't seem to work.

One option might be Jekyll settings in the header about the URL for the page (which can be different to the raw filename)?

Do you think if we rename these files/pages, so that the working tip has Windows friendly filenames, git would be OK on Windows? Or might the history break things? Do you have access to a Linux/Mac machine to setup that experiment? i.e. If we can fix this, do we need to re-write the git history again?

**Comment by MarkusPiotrowski** [comment]
I don't have easy access to Linux/Mac (maybe setting up a virtual box?). Personally, I just forked from biopython.github.io yesterday evening, so for me it would be painless to delete the respositary and start from scratch (what I will do anyway when you 'declare working on biopython.github.io open') . Actually it seems that I'm the only one who has forked yet (since I need to work online -- no Jekyll installed), so I don't think that renaming the files can do much harm? Sorry, I'm not so familiar with the inner details of Git...

**Comment by peterjc** [comment]
We should test using a colon-less filename but a colon in the ``permalink`` setting in the YAML header, https://jekyllrb.com/docs/frontmatter/

If that works I would be happy to re-write the history one more time.

**Comment by peterjc** [comment]
That seems to work, was able to access test example ``http://peterjc.github.io/wiki/User:PeterC`` which was actually from file ``User_PeterC.md`` with this as its header:

```
permalink: /wiki/User:PeterC
title: User:Peter
layout: wiki
tags:
 - People
```

(Note pushing changes to my personal fork ``peterjc.github.io`` gives a warning that the ``CNAME`` isn't used because someone else has already claimed ``biopython.org``, i.e. ``biopython.github.io``)

**Comment by peterjc** [comment]
That should be working now (I had to repeat the import and re-write the git history).

@MarkusPiotrowski can you please try a clean git clone on Windows?

**Comment by MarkusPiotrowski** [comment]
Did work.

**Comment by peterjc** [comment]
Oh good - thanks for confirming. This is a little more complicated, but I agree it is important we don't exclude future Windows contributors (when I first started contributing to Biopython, I mainly used Windows).
