### ISSUE TITLE
Moving old Restriction.html to website as markdown?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#51]
On https://github.com/biopython/biopython.github.io/pull/50 @MarkusPiotrowski had translated https://github.com/biopython/biopython/blob/master/Doc/cookbook/Restriction/Restriction.html into markdown as ``wiki/Restriction.md`` which would put it on the new website as ``http://biopython.org/wiki/Restriction``.

I have temporarily put it as a stand alone commit on a personal branch, see https://github.com/peterjc/peterjc.github.io/tree/restriction and https://github.com/peterjc/peterjc.github.io/commit/8a43a065a6e4065fa101644f82122c976d96f9df which you can read nicely at https://github.com/peterjc/peterjc.github.io/blob/8a43a065a6e4065fa101644f82122c976d96f9df/wiki/Restriction.md

If moving it to the website is a good idea, what should we do with the old raw HTML file?  I would suggest making it redirect to the website or removing it from the source code repository.

I'm wondering if it would be better to integrate the old HTML into the module's docstrings or the tutorial. That way it is still under version control with source code - less important with the small cookbook examples on the website.

However, I would rather spend effort on replacing the whole of ``Bio.Restriction``, see e.g. https://github.com/biopython/biopython/pull/268

**Comment by MarkusPiotrowski** [comment]
The reason why I did start to work on `Restriction.hmtl`in the first place was that there was a page (`Create_an_article_to_this_category`? It's gone now) redirecting to it. If the redirect had worked it had pointed to the html file at [https://github.com/biopython/biopython/blob/master/Doc/cookbook/Restriction/Restriction.html], which will present you the raw html (not quite readable).

Personally, I would prefer to also replace the html page with the markdown page on the Biopython code pages. It's rather lengthy for an inclusion into the tutorial or as docstring?

On the other hand `Restriction` is complex enough to earn some documentation in the wiki. That's why I want to put it there

During the conversion I found an error with `Restricition.suppliers()` and `ranacompiler.py`. I also have problems connecting to REBASE via `rebase_update.py`, I'm trying to fix this and the pull request to come will also address 'Restriction.html`.

As it happened to me with `pairwise2`, I learned that the `Restriction` module is quite powerful, however, it has some strange design decisions and rewriting from scratch or going on with https://github.com/biopython/biopython/pull/268 seems to be a good idea.

**Comment by peterjc** [comment]
Mystery solved - see https://github.com/biopython/biopython.github.io/commit/dd26dafe2a2735bddba5e24c95eccb1648f2176c where the old link was replaced with a (broken) link to ``wiki/Restriction``.

We want to link to http://biopython.org/DIST/docs/cookbook/Restriction.html (which I need to push to https://github.com/biopython/DIST)

**Comment by peterjc** [comment]
Uploaded to the DIST repository with https://github.com/biopython/DIST/commit/78bff38d91b22bdb2d3610f008cc38d3c65f9809 so the old URL works again, http://biopython.org/DIST/docs/cookbook/Restriction.html

@MarkusPiotrowski should we commit your ``Restriction.md`` file to the main Biopython source code repository next to ``Restriction.html`` in case it is useful later on? i.e. Here: https://github.com/biopython/biopython/tree/master/Doc/cookbook/Restriction

**Comment by peterjc** [comment]
The link is working now in http://biopython.org/wiki/Documentation - closing.

**Comment by MarkusPiotrowski** [comment]
Oh, I see, you want to hide it...

Would be nice if you can commit the markdown file next to the html file to the source code repository

**Comment by peterjc** [comment]
@MarkusPiotrowski I may have misunderstood what you meant at the start of this issue - right now the restriction documentation seems to be available again.

Could you make a pull request against https://github.com/biopython/biopython adding ``Doc/cookbook/Restriction/Restriction.md`` (next to the existing file ``Doc/cookbook/Restriction/Restriction.html``)? Or are you happy for me to do it and set the git commit author to be you?

**Comment by MarkusPiotrowski** [comment]
I make the pull request (later), together with some minor issues in the `Restriction` package. Also, as I made some minor changes in `Restriction.md` during conversion, I'll try to incorporate these also in the `html' file.

**Comment by peterjc** [comment]
Thank you - this isn't urgent, so don't rush.

**Comment by MarkusPiotrowski** [comment]
Can we exchange  `Restriction.html` in the  `DIST` respository with the  updated version from the original Biopython respository?

**Comment by peterjc** [comment]
Good point. Done as https://github.com/biopython/DIST/commit/ad129464c68bf79a2c24b2f33ec6b4a2800eff8d - in theory we can take a PR on the DIST repository?
